# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/theo/Desktop/Code-Projekte/engine

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/theo/Desktop/Code-Projekte/engine

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/local/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/theo/Desktop/Code-Projekte/engine/CMakeFiles /Users/theo/Desktop/Code-Projekte/engine//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/theo/Desktop/Code-Projekte/engine/CMakeFiles 0
.PHONY : all

# The main codegen target
codegen: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/theo/Desktop/Code-Projekte/engine/CMakeFiles /Users/theo/Desktop/Code-Projekte/engine//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 codegen
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/theo/Desktop/Code-Projekte/engine/CMakeFiles 0
.PHONY : codegen

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named engine

# Build rule for target.
engine: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 engine
.PHONY : engine

# fast build rule for target.
engine/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/build
.PHONY : engine/fast

src/com/estbComQT.o: src/com/estbComQT.cpp.o
.PHONY : src/com/estbComQT.o

# target to build an object file
src/com/estbComQT.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/com/estbComQT.cpp.o
.PHONY : src/com/estbComQT.cpp.o

src/com/estbComQT.i: src/com/estbComQT.cpp.i
.PHONY : src/com/estbComQT.i

# target to preprocess a source file
src/com/estbComQT.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/com/estbComQT.cpp.i
.PHONY : src/com/estbComQT.cpp.i

src/com/estbComQT.s: src/com/estbComQT.cpp.s
.PHONY : src/com/estbComQT.s

# target to generate assembly for a file
src/com/estbComQT.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/com/estbComQT.cpp.s
.PHONY : src/com/estbComQT.cpp.s

src/datapull/pullDataSpdr.o: src/datapull/pullDataSpdr.cpp.o
.PHONY : src/datapull/pullDataSpdr.o

# target to build an object file
src/datapull/pullDataSpdr.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/datapull/pullDataSpdr.cpp.o
.PHONY : src/datapull/pullDataSpdr.cpp.o

src/datapull/pullDataSpdr.i: src/datapull/pullDataSpdr.cpp.i
.PHONY : src/datapull/pullDataSpdr.i

# target to preprocess a source file
src/datapull/pullDataSpdr.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/datapull/pullDataSpdr.cpp.i
.PHONY : src/datapull/pullDataSpdr.cpp.i

src/datapull/pullDataSpdr.s: src/datapull/pullDataSpdr.cpp.s
.PHONY : src/datapull/pullDataSpdr.s

# target to generate assembly for a file
src/datapull/pullDataSpdr.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/datapull/pullDataSpdr.cpp.s
.PHONY : src/datapull/pullDataSpdr.cpp.s

src/datapull/pullDataUsr.o: src/datapull/pullDataUsr.cpp.o
.PHONY : src/datapull/pullDataUsr.o

# target to build an object file
src/datapull/pullDataUsr.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/datapull/pullDataUsr.cpp.o
.PHONY : src/datapull/pullDataUsr.cpp.o

src/datapull/pullDataUsr.i: src/datapull/pullDataUsr.cpp.i
.PHONY : src/datapull/pullDataUsr.i

# target to preprocess a source file
src/datapull/pullDataUsr.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/datapull/pullDataUsr.cpp.i
.PHONY : src/datapull/pullDataUsr.cpp.i

src/datapull/pullDataUsr.s: src/datapull/pullDataUsr.cpp.s
.PHONY : src/datapull/pullDataUsr.s

# target to generate assembly for a file
src/datapull/pullDataUsr.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/datapull/pullDataUsr.cpp.s
.PHONY : src/datapull/pullDataUsr.cpp.s

src/io/parseConfig.o: src/io/parseConfig.cpp.o
.PHONY : src/io/parseConfig.o

# target to build an object file
src/io/parseConfig.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/io/parseConfig.cpp.o
.PHONY : src/io/parseConfig.cpp.o

src/io/parseConfig.i: src/io/parseConfig.cpp.i
.PHONY : src/io/parseConfig.i

# target to preprocess a source file
src/io/parseConfig.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/io/parseConfig.cpp.i
.PHONY : src/io/parseConfig.cpp.i

src/io/parseConfig.s: src/io/parseConfig.cpp.s
.PHONY : src/io/parseConfig.s

# target to generate assembly for a file
src/io/parseConfig.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/io/parseConfig.cpp.s
.PHONY : src/io/parseConfig.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... codegen"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... engine"
	@echo "... src/com/estbComQT.o"
	@echo "... src/com/estbComQT.i"
	@echo "... src/com/estbComQT.s"
	@echo "... src/datapull/pullDataSpdr.o"
	@echo "... src/datapull/pullDataSpdr.i"
	@echo "... src/datapull/pullDataSpdr.s"
	@echo "... src/datapull/pullDataUsr.o"
	@echo "... src/datapull/pullDataUsr.i"
	@echo "... src/datapull/pullDataUsr.s"
	@echo "... src/io/parseConfig.o"
	@echo "... src/io/parseConfig.i"
	@echo "... src/io/parseConfig.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

